#!/bin/bash
# Stage 1.5 Alpha Survey Usage Examples (Batch API Mode)

echo "======================================"
echo "Stage 1.5 Alpha Survey Usage Examples"
echo "======================================"
echo ""
echo "💰 Default: Batch API + Reason축약 = 63% cost savings"
echo "   Cost: \$53.29 for 9,200 personas (vs \$143.37 baseline)"
echo ""

# Example 1: Basic usage (recommended)
echo "Example 1: Basic Usage (Recommended)"
echo "------------------------------------"
echo "Submit batch job and wait for completion"
echo ""
echo "Command:"
echo "python run_stage1_5.py"
echo ""
echo "This will:"
echo "  1. Collect all prompts from Stage 1 outputs"
echo "  2. Submit batch job to OpenAI"
echo "  3. Wait for completion (polls every 60s)"
echo "  4. Download and save results"
echo "  5. Show 63% cost savings"
echo ""
echo "======================================"
echo ""

# Example 2: Submit and check later
echo "Example 2: Submit and Check Later"
echo "----------------------------------"
echo "Submit batch job and resume later (for long-running jobs)"
echo ""
echo "Step 1 - Submit job and exit:"
echo "python run_stage1_5.py --no_wait"
echo ""
echo "Step 2 - Resume later (after 1-24 hours):"
echo "python run_stage1_5.py --resume_batch_id \$(cat outputs/stage1_5_batch/alpha_survey_batch_id.txt)"
echo ""
echo "======================================"
echo ""

# Example 3: Test with limited records
echo "Example 3: Test with Limited Records"
echo "-------------------------------------"
echo "Test with 10 records (~92 personas)"
echo ""
echo "Command:"
echo "python run_stage1_5.py --max_records 10"
echo ""
echo "Cost estimate: ~\$0.58 (vs \$1.56 baseline)"
echo ""
echo "======================================"
echo ""

# Example 4: Custom directories
echo "Example 4: Custom Directories"
echo "------------------------------"
echo ""
echo "Command:"
echo "python run_stage1_5.py \\"
echo "  --stage1_dir outputs/stage1/test/data \\"
echo "  --out_dir outputs/stage1_5/test/data \\"
echo "  --batch_dir outputs/stage1_5_batch"
echo ""
echo "======================================"
echo ""

# Example 5: Re-process existing outputs
echo "Example 5: Re-process Existing Outputs"
echo "---------------------------------------"
echo "Force re-processing (ignore existing Stage 1.5 outputs)"
echo ""
echo "Command:"
echo "python run_stage1_5.py --no_resume"
echo ""
echo "======================================"
echo ""

# Example 6: Use GPT-4.1-mini (budget option)
echo "Example 6: Budget Option (GPT-4.1-mini)"
echo "----------------------------------------"
echo "Use GPT-4.1-mini for maximum cost savings (85%)"
echo ""
echo "Command:"
echo "python run_stage1_5.py --model gpt-4.1-mini"
echo ""
echo "Cost: \$21.31 for 9,200 personas (vs \$143.37 baseline)"
echo "Note: Lower quality than GPT-4.1"
echo ""
echo "======================================"
echo ""

# Cost summary
echo "Cost Summary (1000 files, 9,200 personas)"
echo "=========================================="
printf "%-40s | %-10s | %-10s\n" "Mode" "Cost" "Savings"
echo "--------------------------------------------------------------------------------"
printf "%-40s | %-10s | %-10s\n" "Baseline (no optimization)" "\$143.37" "-"
printf "%-40s | %-10s | %-10s\n" "Batch API + Reason축약 (Default)" "\$53.29" "63% ✅"
printf "%-40s | %-10s | %-10s\n" "GPT-4.1-mini + Batch + Reason축약" "\$21.31" "85%"
echo ""
echo "======================================"
echo ""

# Workflow
echo "Typical Workflow"
echo "================"
echo ""
echo "1. Test with small batch:"
echo "   python run_stage1_5.py --max_records 10"
echo ""
echo "2. Submit full production batch:"
echo "   python run_stage1_5.py --no_wait"
echo ""
echo "3. Check status (after a few hours):"
echo "   python run_stage1_5.py --resume_batch_id \$(cat outputs/stage1_5_batch/alpha_survey_batch_id.txt)"
echo ""
echo "4. Verify outputs:"
echo "   ls -lh outputs/stage1_5/test/data/"
echo ""
echo "======================================"
